@baseURL = http://localhost:8000

###
# @name listPeople
GET {{baseURL}}/api/person

###
# @name createPerson
POST {{baseURL}}/api/person
Content-Type: application/json

{
    "name": "Joelton Porto",
    "email": "joeltonportolima@gmail.com",
    "phone": "63984193244"
}
